# Generated by Django 6.0.1 on 2026-01-21 03:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mystery_Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('estado', models.CharField(choices=[('A', 'Activa'), ('I', 'Inactivo')], default='A', max_length=20)),
                ('porcentaje_descuento', models.IntegerField(choices=[(0, 'Sin Descuento'), (5, 'Descuento Basico (5%)'), (10, 'Descuento Estandar (10%)'), (15, 'Gran descuento(15%)'), (20, 'Super descuento (20%)')], default=10)),
                ('es_exclusiva', models.BooleanField(default=False)),
                ('allowed_categories', models.ManyToManyField(related_name='boxes', to='store.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('categoria', models.ManyToManyField(related_name='productos', to='store.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateField(default=django.utils.timezone.now)),
                ('direccion_envio', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_receptor', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('P', 'Preparando caja'), ('E', 'Enviado'), ('R', 'Recibido')], default='P')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('codigo_rastreo_interno', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_guia', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_envios', to=settings.AUTH_USER_MODEL)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.mystery_box')),
                ('productos', models.ManyToManyField(related_name='envios', to='store.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('A', 'Activa'), ('C', 'Cancelada'), ('P', 'Pago_pendiente')], max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_proximo_pago', models.DateField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='membresia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
