# Generated by Django 5.2.8 on 2026-01-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystery_box',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
