# Generated by Django 5.2.8 on 2026-01-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_mystery_box_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
