# Generated by Django 6.0.1 on 2026-01-21 05:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_categoria_activa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='fecha_envio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='estado',
            field=models.CharField(choices=[('I', 'Inactiva'), ('A', 'Activa'), ('C', 'Cancelada'), ('P', 'Pago_pendiente')], default='I', max_length=20),
        ),
    ]
