# Generated by Django 6.0.1 on 2026-01-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_envio_fecha_envio_alter_suscripcion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
