# Generated by Django 5.2.8 on 2026-01-05 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_producto_categoria_producto_categorias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categorias',
            new_name='categoria',
        ),
    ]
