# Generated by Django 6.0.1 on 2026-01-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_carritoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código del cupón')),
                ('descuento_porcentaje', models.IntegerField(default=0, help_text='Descuento en porcentaje (0-100)')),
                ('descuento_fijo', models.DecimalField(decimal_places=2, default=0, help_text='Descuento fijo en dólares', max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_expiracion', models.DateTimeField()),
                ('usos_maximos', models.IntegerField(blank=True, help_text='Dejar vacío para usos ilimitados', null=True)),
                ('usos_actuales', models.IntegerField(default=0)),
                ('solo_premium', models.BooleanField(default=False, help_text='Solo para usuarios premium')),
                ('monto_minimo', models.DecimalField(decimal_places=2, default=0, help_text='Monto mínimo de compra', max_digits=10)),
            ],
        ),
    ]
