# Generated by Django 6.0.1 on 2026-01-18 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_categorias_producto_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='envios',
            name='productos',
            field=models.ManyToManyField(related_name='envios', to='store.producto'),
        ),
        migrations.AlterField(
            model_name='envios',
            name='suscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envio', to='store.suscripcion'),
        ),
        migrations.AlterField(
            model_name='mystery_box',
            name='allowed_categories',
            field=models.ManyToManyField(related_name='boxes', to='store.categoria'),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='store.mystery_box'),
        ),
    ]
