# Generated by Django 6.0.1 on 2026-01-21 07:53

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCupon',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50, verbose_name='Código del cupón')),
                ('descuento_porcentaje', models.IntegerField(default=0, help_text='Descuento en porcentaje (0-100)')),
                ('descuento_fijo', models.DecimalField(decimal_places=2, default=0, help_text='Descuento fijo en dólares', max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_expiracion', models.DateTimeField()),
                ('usos_maximos', models.IntegerField(blank=True, help_text='Dejar vacío para usos ilimitados', null=True)),
                ('usos_actuales', models.IntegerField(default=0)),
                ('solo_premium', models.BooleanField(default=False, help_text='Solo para usuarios premium')),
                ('monto_minimo', models.DecimalField(decimal_places=2, default=0, help_text='Monto mínimo de compra', max_digits=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical cupon',
                'verbose_name_plural': 'historical cupons',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
