# Generated by Django 6.0.1 on 2026-01-18 20:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_producto_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('P', 'Preparando caja'), ('E', 'Enviado'), ('R', 'Recibido')], default='P')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('numero_guia', models.CharField(blank=True, max_length=50, null=True)),
                ('productos', models.ManyToManyField(related_name='envios', to='store.producto')),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envio', to='store.suscripcion')),
            ],
        ),
        migrations.DeleteModel(
            name='Envios',
        ),
    ]
