# Generated by Django 6.0.1 on 2026-01-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_envio_delete_envios'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystery_box',
            name='estado',
            field=models.CharField(choices=[('A', 'Activa'), ('I', 'Inactivo')], default='A', max_length=20),
        ),
    ]
