# Generated by Django 6.0.1 on 2026-01-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_cuponuso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_iva', models.DecimalField(decimal_places=2, default=15.0, help_text='Porcentaje de IVA actual (ej. 15.00)', max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='envio',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='envio',
            name='monto_impuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='envio',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
