# Generated by Django 6.0.1 on 2026-01-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_mystery_box_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='direccion_envio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='pais',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
