# Generated by Django 6.0.1 on 2026-01-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_configuracion_envio_iva_porcentaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si se desactiva, no se usará en nuevas cajas.'),
        ),
    ]
