# Generated by Django 6.0.1 on 2026-01-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_envio_ciudad_envio_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='nombre_receptor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
