# Generated by Django 6.0.1 on 2026-03-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_producto_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='costo_contenido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='envio',
            name='valor_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
