# Generated by Django 6.0.1 on 2026-01-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_envio_nombre_receptor'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='codigo_rastreo_interno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
